"""add likes

Revision ID: 0c68c915deb2
Revises: a4b26f475f57
Create Date: 2025-04-01 08:32:17.261872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c68c915deb2'
down_revision = 'a4b26f475f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('comment_liker_id', sa.Integer(), nullable=True),
    sa.Column('liked_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_liker_id'], ['users.id'], name=op.f('fk_likes_comment_liker_id_users')),
    sa.ForeignKeyConstraint(['liked_comment_id'], ['comments.id'], name=op.f('fk_likes_liked_comment_id_comments')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
