"""add reply likes

Revision ID: 7746dc7cf349
Revises: 0c68c915deb2
Create Date: 2025-04-01 08:50:18.274994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7746dc7cf349'
down_revision = '0c68c915deb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('reply_liker_id', sa.Integer(), nullable=True),
    sa.Column('liked_reply_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liked_reply_id'], ['replies.id'], name=op.f('fk_reply_likes_liked_reply_id_replies')),
    sa.ForeignKeyConstraint(['reply_liker_id'], ['users.id'], name=op.f('fk_reply_likes_reply_liker_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply_likes')
    # ### end Alembic commands ###
