"""add commenter

Revision ID: ea44fe2a01f6
Revises: 90b70f24ebcb
Create Date: 2025-03-31 22:07:20.113475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea44fe2a01f6'
down_revision = '90b70f24ebcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commenter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comments_commenter_id_users'), 'users', ['commenter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_commenter_id_users'), type_='foreignkey')
        batch_op.drop_column('commenter_id')

    # ### end Alembic commands ###
